[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llmverse"
version = "0.1.3"
authors = [
  { name="Nilavo Boral", email="nilavoboral@gmail.com" },
]
description = "LLM-Universe: One-Stop Solution for All Open-Source LLMs, from Downloading and Quantizing to Generating Responses and Fine-Tuning."
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["packaging", "wheel", "pandas", "matplotlib", "torch", "transformers", "peft", "datasets", "bitsandbytes", "accelerate", "flash_attn", "sentencepiece", "wandb"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]