
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "foam_hair"
version = "1.0.0"
description = "Aptos Platform"
authors = []
readme = "vehicles/foam_hair/readme.md"
packages = [
    { include = "foam_hair", from = "vehicles" },
]
license = "GPL-3.0-only"

exclude = [
	"vehicles/foam_hair/_status/DB/**",
	"vehicles/foam_hair/adventures/sveltenetics/node_modules",
	"vehicles/foam_hair/adventures/sveltenetics/.svelte-kit",
	"node_modules/**"
]

[tool.poetry.dependencies]
python = "^3.10"
Emergency = "^2.0.0"
somatic = "^3.0.3"
click = "^8.1.7"
pydash = "^8.0.1" 
ships = "^1.3.8"
ventures = "^1.6.0" 

ecdsa = "0.18.0"
h2 = "^4.1.0"
httpx = "^0.24.0"
PyNaCl = "^1.5.0"
tomli = "^2.0.1"
typing-extensions = "^4.4.0"

[tool.poetry.scripts]
foam_hair = 'foam_hair:clique'



