[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "black>=24.4.2",
    "build>=1.2.1",
    "isort>=5.9.3",
    "packaging>=23.2",
    "requests>=2.31.0",
    "tomlhold>=0.0.3",
    "tomli-w>=1.0.0",
    "twine>=5.1.1",
]
description = "petrus"
keywords = []
name = "petrus"
readme = "README.rst"
requires-python = ">=3.12.4"
version = "0.0.23"

[project.license]
file = "LICENSE.txt"

[project.urls]
Download = "https://pypi.org/project/petrus/#files"
Source = "https://github.com/johannes-programming/petrus"
