[project]
name = "campbell_quest"
version = "0.0.28"
authors = [
  { name="Jasfiq Rahman", email="jasfiqrahman15@gmail.com" },
]
description = "A procedural quest generation system."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["ollama", "langchain", "langchain_core", "langchain_community"]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"