[tool.poetry]
name = "rms-models"
version = "0.0.15"
description = "Models for RMS System"
authors = ["AlexGat27 <aleksandrgataulin745@gmail.com>"]
readme = "README.md"
exclude = ["rms_models/_internal/*"]

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.13.2"
pydantic = "^2.9.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.3"
mypy = "^1.11.2"
black = "^24.8.0"
sqlalchemy = "^2.0.32"
python-dotenv = "^1.0.1"
asyncpg = "^0.29.0"

[tool.poetry.extras]
dev = ["alembic", "python-dotenv", "asyncpg"]

[tool.poetry.urls]
"Repository" = "http://git.vald.ai:8282/rms/rms_models.git"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
