[tool.poetry]
name = "my-test-python-project"
version = "0.2.1"
description = ""
authors = ["ihrskyfish <ihr17867950748@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




