[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "scaevola>=1.0.5",
]
description = "mutable version objects"
keywords = []
name = "v440"
readme = "README.rst"
requires-python = ">=3.12"
version = "0.0.9"

[project.license]
file = "LICENSE.txt"

[project.urls]
Download = "https://pypi.org/project/v440/#files"
Source = "https://github.com/johannes-programming/v440"
