[tool.poetry]
name = "PyCAMPs"
version = "0.0.1"
description = "Centralized Automated Modeling of Power Systems in Python"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "3.9.2"
mpmath = "1.3.0"
numpy = "2.1.0"
pytest = "8.3.2"
scipy = "1.14.1"
sympy = "1.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
