[project]
name = "rolling_ta"
version = "0.5"
authors = [
    {name="Kwuasimoto", email="thomasdouglasshank@gmail.com"}
]
description = "Simple, lightweight single responsibility API for performing near-incremental technical analysis indicator calculations using Pandas."
dependencies = ["pandas==2.2.2"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = ["rolling_ta"]

[project.urls]
Homepage = "https://github.com/Kwuasimoto/test-pypi"

[project.optional-dependencies]
dev = ["black"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = ["/.*", "/tests"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

log_file = "pytest.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
