[tool.poetry]
name = "cmem-plugin-base"
version = "4.8.0"
license = "Apache-2.0"
description = "Base classes for developing eccenca Corporate Memory plugins."
authors = ["eccenca <cmempy-developer@eccenca.com>"]
maintainers = [
    "Sebastian Tramp <sebastian.tramp@eccenca.com>",
    "Robert Isele <robert.isele@eccenca.com>"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
readme = "README-public.md"
keywords = [
    "eccenca Corporate Memory", "plugins", "DataIntegration"
]

[tool.poetry.dependencies]
python = "^3.11"
cmem-cmempy = ">=23.3.0"
python-ulid = "^2.2.0"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.5"
black = "^24"
pip = "^24"
coverage = "^7.2.7"
defusedxml = "^0.7.1"
flake8-formatter-junit-xml = "^0.0.6"
genbadge = "^1.1.0"
mypy = "^1.4.1"
# https://github.com/rasjani/pylint-junit/issues/1
pylint = "^2"
pylint-junit = "^0.3.2"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-memray = "^1.4.1"
safety = "^1.10.3"
typed-ast = "^1.5.4"
types-requests = "^2.31.0.1"
wheel = "^0.38.4"
# added in order to have something to discover (>=0.0.0 <1.0.0)
# cmem-plugin-examples = "*"
pytest-dotenv = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
dirty = true

[tool.pylint.MASTER]
load-plugins="pylint_junit"

[tool.pylint.General]
ignore = "version.py"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
disable = "fixme"

# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#pylint
[tool.pylint.messages_control]
disable = "R0903"

[tool.pylint.format]
max-line-length = "88"
disable = ""
max-args = "8"
max-attributes = "9"

[tool.mypy]
warn_return_any = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "cmem_plugin_base.dataintegration.context",
    "cmem_plugin_base.dataintegration.plugins",
    "cmem_plugin_base.dataintegration.types"
]
disable_error_code = "empty-body"

[tool.pytest.ini_options]
addopts = ""

